<a href="https://colab.research.google.com/github/h-yamani/docs/blob/main/1.first_torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
torch.linspace(3,10,steps=5)

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [4]:
torch.arange(0,5)

tensor([0, 1, 2, 3, 4])

In [5]:
torch.rand(2,3)

tensor([[0.7775, 0.0784, 0.6520],
        [0.6943, 0.2302, 0.7278]])

In [7]:
a =torch.rand(2,3)
b =torch.rand(3,2)
torch.mm(a,b)

tensor([[0.8869, 0.0833],
        [1.5679, 0.1147]])

In [6]:
from torch.autograd import Variable

In [9]:

x = Variable(torch.FloatTensor([11.2]), requires_grad=True)
y = 2 * x
print(x)
print(y)
y.backward()
print(y.grad)
print(x.grad)

tensor([11.2000], requires_grad=True)
tensor([22.4000], grad_fn=<MulBackward0>)
None
tensor([2.])


/usr/local/lib/python3.7/dist-packages/torch/_tensor.py:1013: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  aten/src/ATen/core/TensorBody.h:417.)
  return self._grad
