<a href="https://colab.research.google.com/github/h-yamani/docs/blob/main/tensors_and_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Working with PyTorch and NumPy

In [1]:
import torch
import numpy as np

Convert a NumPy array to Tensor

In [2]:
n = np.array([2, 3])
t = torch.from_numpy(n)
print(n)
print(t)

[2 3]
tensor([2, 3])


Change a Tensor value, and see the change in 
corresponding NumPy array

In [3]:
n[0] = 100
print(t)

tensor([100,   3])


Convert a Tensor to NumPy array

In [4]:
t = torch.FloatTensor([5, 6])
n = t.numpy()
print(t)
print(n)

tensor([5., 6.])
[5. 6.]


Change a Tensor value, and see the change in corresponding NumPy array

In [5]:
t[0] = 100
print(n)

[100.   6.]
